### PR TITLE
FEATURE: Add a links dropdown based on values passed

### PR DESCRIPTION
**Pull request by fzngagan**
Usage instructions
First 5 sections of the settings are for the existing functionality
From 5th onwards just add `...~url~linkname~url~linkname...`and each of the url,linkname pair will become a dropdown item

if this part is ignored, the component will behave normally

### CODE REVIEW

**Review by angusmcleod — CHANGES_REQUESTED** [review]
@fzngagan Hey, in general this is great work. Love the use of the widget templates. One small note on the formatting. All object literal properties should be on a new line, e.g.

```
contents.push({
   id: Math.floor(Math.random() * 100),
   html: `<a href=${linkData[i]}>${linkData[i+1]}</a>`
})
```
I don't think the logic quite works for Carson's requirement however. He's imagining a single dropdown that will contain a list of topic links in sub-categories of premium content that the user has access to. This means the list should be different for different users. Currently the dropdown is going to be the same for every user. 

For example, if I had one entry in the ``highlight_categories`` setting tied to the premium-content category and a list of conference topic links as the 5th item, the same list would show for all users, but not all users would be able to access every link.

I think we just need to tweak the logic here slightly to take advantage of the sub-categories permissions in deciding which links get added to the dropdown. Rather than listing the dropdown items statically on the end of an item, we should add two new parts to the settings string:

**Parent item, type: category slug**. If a category slug is included here the item will appear in a dropdown associated with the parent item, identified by slug. So for example

```
premium-content~#fff~#009000~:star:&nbsp;&nbsp;<b>Premium Content</b>~:star:
premium-content/sub-cat-a~#333~#009000~:cross:&nbsp;&nbsp;<b>Sub Cat</b>~:star:~premium-content
```

Note the ``premium-content`` slug as the fifth item on the second string. This would mean that the entry for sub-cat-a would become a menu item in a dropdown menu associated with premium-content, but only if the user had access to sub-cat-a, i.e. only if the category was present in the user's category list.

**Alternate link, type: url or path**. To deal with linking to topics instead of to the category, we'd introduce a sixth item in the setting string, alternate link. If a path or url was entered here the category's element in the header (whether it was a parent element, or part of a dropdown) would link to the alternate link instead of to the category.

Both additional settings would also work separately or jointly for other use cases.

**Comment by angusmcleod** [comment]
@fzngagan How's this one going?

**Comment by fzngagan** [comment]
@angus I'm close here.

**Comment by fzngagan** [comment]
@angusmcleod I've just pushed the code. It should work exactly as you described in the spec. 

A few strings to test. Just replace the category slugs and labels
`staff~linear-gradient(319deg, #cdedfd 0%, #ffec82 37%, #ffcfd2 100%)~#ff0000~:star:&nbsp&nbspStaff~:star:`

`tbs-dev~linear-gradient(319deg, #cdedfd 0%, #ffec82 37%, #ffcfd2 100%)~#88562e~:star:&nbsp&nbspTBS~:star:~~https://google.com`

`events~linear-gradient(319deg, #cdedfd 0%, #ffec82 37%, #ffcfd2 100%)~#88562e~:star:&nbsp&nbspEvents~:star:`

`events/events-sub-cat~linear-gradient(319deg, #cdedfd 0%, #ffec82 37%, #ffcfd2 100%)~#88562e~:star:&nbsp&nbspTBS~:star:~events~/t/external-oauth2-using-the-discourse-signin-page-discourse-meta-latest-topics/584`

**Comment by angusmcleod** [comment]
@fzngagan Ok merging :+1: I just fixed up some of the space formatting.

As mentioned, good work :+1:

Could you take a look at prettier? Maybe chat with Rob about it. Your code formatting is still not quite right and that could help.

**Pull request merged**
